name: Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/wonmart-mobile-v1.apk

      - name: Upload Renamed APK to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/wonmart-mobile-v1.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
